version: '3.4'

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: RabbitMQ

  web.apigateway:
    image: ${DOCKER_REGISTRY-}webapigateway
    build:
      context: .
      dockerfile: ApiGateways/Web/Web.ApiGateway/Dockerfile

  post:
    image: ${DOCKER_REGISTRY-}post
    build:
      context: .
      dockerfile: Services/Post/Dockerfile

  user:
    image: ${DOCKER_REGISTRY-}user
    build:
      context: .
      dockerfile: Services/User/Dockerfile