version: '3.4'

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: RabbitMQ

  postgres:
    image: postgres:latest
    container_name: Postgres

  apigatewayweb:
    image: ${DOCKER_REGISTRY-}apigatewayweb
    build:
      context: .
      dockerfile: ApiGateways/Web/ApiGateway.Web/Dockerfile
    depends_on:
      - postapi
      - userapi
      - financialapi

  postapi:
    image: ${DOCKER_REGISTRY-}postapi
    build:
      context: .
      dockerfile: Services/Post/Post.Api/Dockerfile
    depends_on:
      - rabbitmq
      - postgres

  userapi:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: Services/User/User.Api/Dockerfile
    depends_on:
      - rabbitmq
      - postgres

  financialapi:
    image: ${DOCKER_REGISTRY-}financialapi
    build:
      context: .
      dockerfile: Services/Financial/Financial.Api/Dockerfile
    depends_on:
      - rabbitmq